<form method="post">
    <div class="form-row">
        <label for="username">Benutzername</label>
        <label for="password">Kennwort</label>
    </div>

    <div class="form-row">
        <input id="username" autocomplete="username" type="text" name="username">
        <input id="password" autocomplete="current-password" type="password" name="password">
        <input type="submit" value="anmelden">
    </div>
</form>
